name: Develop

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.0
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: Run build task
        run: pnpm build
      - name: zip bundle file
        run: cd .output/chrome-mv3 && zip -r ctx.zip . && mv ctx.zip ../../
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ctx
          path: ctx.zip